[workspace]
resolver = "2"
members = [
    "crates/scan-kit-core",
    "crates/scan-kit-mcp",
    "apps/desktop/src-tauri",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

[workspace.package]
version = "2.0.0-dev"
edition = "2021"
license = "MIT"
publish = false
authors = ["Pyramid Technical Consultants, Inc. <support@ptcusa.com>"]

[workspace.dependencies]
scan-kit-core = { path = "crates/scan-kit-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-std", "io-util"] }
