"""Common utilities for scan-kit analysis scripts."""

from .session_meta import SessionMeta, parse_termination_summary_text
from .session_source import (
    SessionSource,
    resolve_session_source,
    load_session_csv,
    load_session_timeslice_device_units,
    load_session_termination_summary,
    hydrate_session_metadata,
    discover_session_entries,
)
from .transform import remap, IC1_X_MAP, IC1_Y_MAP, IC2_X_MAP, IC2_Y_MAP
from .validation import create_valid_mask, apply_validation
from .processing import load_session_raw, process_position_data
from .plotting import (
    plot_boxplots_for_column,
    plot_scatter_energy,
    add_energy_colorbar,
    annotate_slopes,
    make_session_legend,
    style_energy_axes,
    link_boxplot_to_histogram,
    DEFAULT_SESSION_COLORS,
    FIG_SIZE_2x2,
    FIG_SIZE_1x2,
    FIG_SIZE_SINGLE,
    SUPTITLE_KW,
    GRID_KW,
    REFLINE_KW,
    SCATTER_ALPHA,
    SCATTER_SIZE,
    SLOPE_LABEL_KW,
    SLOPE_LABEL_BOX,
)

__all__ = [
    "SessionMeta",
    "parse_termination_summary_text",
    "SessionSource",
    "resolve_session_source",
    "load_session_csv",
    "load_session_timeslice_device_units",
    "load_session_termination_summary",
    "hydrate_session_metadata",
    "discover_session_entries",
    "remap",
    "IC1_X_MAP",
    "IC1_Y_MAP",
    "IC2_X_MAP",
    "IC2_Y_MAP",
    "create_valid_mask",
    "apply_validation",
    "load_session_raw",
    "process_position_data",
    "plot_boxplots_for_column",
    "plot_scatter_energy",
    "add_energy_colorbar",
    "annotate_slopes",
    "make_session_legend",
    "style_energy_axes",
    "link_boxplot_to_histogram",
    "DEFAULT_SESSION_COLORS",
    "FIG_SIZE_2x2",
    "FIG_SIZE_1x2",
    "FIG_SIZE_SINGLE",
    "SUPTITLE_KW",
    "GRID_KW",
    "REFLINE_KW",
    "SCATTER_ALPHA",
    "SCATTER_SIZE",
    "SLOPE_LABEL_KW",
    "SLOPE_LABEL_BOX",
]
