import {
  Activity,
  ArrowDown,
  ArrowLeftRight,
  ArrowUp,
  Atom,
  AudioLines,
  BadgeCheck,
  Bolt,
  ChartArea,
  ChartScatter,
  Circle,
  CircleAlert,
  CircleDot,
  CircleOff,
  Clock,
  Crosshair,
  Gauge,
  Grid3x3,
  Hash,
  Layers,
  Magnet,
  Minus,
  MoveHorizontal,
  MoveVertical,
  Palette,
  Percent,
  Radius,
  Rainbow,
  Scale,
  Scan,
  Spline,
  Square,
  Target,
  Timer,
  TrendingUp,
  TriangleAlert,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "Dose Error (%)": Percent,
  "Dose Ratios": Scale,
  "Dose Rate (MU/s)": Gauge,
  "Current Ratios (%)": Percent,
  "IC Current (nA)": Zap,
  "Fit Confidence": BadgeCheck,
  "Peak Amplitude": Activity,
  "Amplifier Error (V)": Bolt,
  "Probe Field (G)": Magnet,
  "Position Error (mm)": Crosshair,
  Position: Crosshair,
  "Position Error": Crosshair,
  Sigma: CircleDot,
  Confidence: BadgeCheck,
  Coverage: Scan,
  Density: Grid3x3,
  Turbo: Rainbow,
  Viridis: Palette,
  "Sigma (mm)": CircleDot,
  "Sigma Error (mm)": CircleAlert,
  "IC2-IC1 Position (mm)": ArrowLeftRight,
  "Spot Delivery Time": Timer,
  Energy: Atom,
  "Target MU": Target,
  "Spot time": Timer,
  Radius,
  Violin: AudioLines,
  Box: Square,
  Mean: Minus,
  Scatter: ChartScatter,
  Contour: ChartArea,
  Spot: CircleDot,
  Timeslice: Clock,
  IC1: Zap,
  IC2: Zap,
  "ISO Ray": Crosshair,
  Plan: Target,
  Dose: Gauge,
  MU: Target,
  Protons: Atom,
  Analytic: Spline,
  "Monte Carlo": Atom,
  Water: Circle,
  Measured: Circle,
  Difference: ArrowLeftRight,
  Gamma: CircleAlert,
  Isocenter: Crosshair,
  Chamber: Square,
  "Spot — Isocenter": Crosshair,
  "Spot — Chamber": Square,
  "Timeslice — Isocenter": Clock,
  "Timeslice — Chamber": Clock,
  "Beam On": Circle,
  "Beam Off": CircleOff,
  Both: CircleDot,
  All: Layers,
  Automatic: Layers,
  Off: CircleOff,
  On: Circle,
  Linear: TrendingUp,
  Polynomial: Spline,
  "Lower 95%": ArrowDown,
  "Upper 5%": ArrowUp,
  "MAD Outliers": TriangleAlert,
  position: Crosshair,
  position_error: Crosshair,
  sigma: CircleDot,
  confidence: BadgeCheck,
  coverage: Scan,
  dose_error: Percent,
  dose_ratio: Scale,
  current_ratio: Percent,
  ic_current: Zap,
  fit_confidence: BadgeCheck,
  peak_amplitude: Activity,
  amplifier_error: Bolt,
  amplifier: Bolt,
  probe_field: Magnet,
  probe: Magnet,
  sigma_error: CircleAlert,
  ic12_pos_diff: ArrowLeftRight,
  spot_time: Timer,
  energy: Atom,
  target_mu: Target,
  radius: Radius,
  move_horizontal: MoveHorizontal,
  move_vertical: MoveVertical,
  spot: CircleDot,
  timeslice: Clock,
  all: Layers,
  on: Circle,
  off: CircleOff,
  scatter: ChartScatter,
  density: Grid3x3,
  ic1_current: Zap,
  ic2_current: Zap,
  ic3_current: Zap,
  "IC1 Current": Zap,
  "IC2 Current": Zap,
  "IC3 Current": Zap,
  "Field X": MoveHorizontal,
  "Field Y": MoveVertical,
  "IC1 X": MoveHorizontal,
  "IC1 Y": MoveVertical,
  "IC2 X": MoveHorizontal,
  "IC2 Y": MoveVertical,
  "IC1 X Error": Crosshair,
  "IC1 Y Error": Crosshair,
  "IC2 X Error": Crosshair,
  "IC2 Y Error": Crosshair,
  "IC1 Sigma X": CircleDot,
  "IC1 Sigma Y": CircleDot,
  "IC2 Sigma X": CircleDot,
  "IC2 Sigma Y": CircleDot,
  "IC1 X Confidence": BadgeCheck,
  "IC1 Y Confidence": BadgeCheck,
  "IC2 X Confidence": BadgeCheck,
  "IC2 Y Confidence": BadgeCheck,
  "IC1 X Peak": Activity,
  "IC1 Y Peak": Activity,
  "IC2 X Peak": Activity,
  "IC2 Y Peak": Activity,
  "Amplifier X": Bolt,
  "Amplifier Y": Bolt,
  dose_rate: Gauge,
  sigma_x: CircleDot,
  sigma_y: CircleDot,
  position_x: MoveHorizontal,
  position_y: MoveVertical,
  position_error_x: MoveHorizontal,
  position_error_y: MoveVertical,
  field_x: MoveHorizontal,
  field_y: MoveVertical,
  spot_no: Hash,
  layer_id: Layers,
  r_ic1_x_confidence: BadgeCheck,
};

export function optionIcon(name: string): LucideIcon | undefined {
  const bare = name.replace(/ \((?:Isocenter|Chamber)\)$/, "");
  return ICONS[name] ?? ICONS[bare];
}
