import {
  ArrowDown,
  ArrowLeftRight,
  ArrowUp,
  Atom,
  AudioLines,
  BadgeCheck,
  ChartArea,
  ChartScatter,
  Circle,
  CircleAlert,
  CircleDot,
  CircleOff,
  Clock,
  Crosshair,
  Gauge,
  Hash,
  Layers,
  Minus,
  MoveHorizontal,
  MoveVertical,
  Percent,
  Radius,
  Scale,
  Scan,
  Square,
  Target,
  Timer,
  TriangleAlert,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "Dose Error (%)": Percent,
  "Dose Ratios": Scale,
  "Dose Rate (MU/s)": Gauge,
  "Current Ratios (%)": Percent,
  "IC Current (nA)": Zap,
  "Position Error (mm)": Crosshair,
  "Sigma (mm)": CircleDot,
  "Sigma Error (mm)": CircleAlert,
  "IC2-IC1 Position (mm)": ArrowLeftRight,
  "Spot Delivery Time": Timer,
  Energy: Atom,
  "Target MU": Target,
  "Spot time": Timer,
  Radius,
  Violin: AudioLines,
  Box: Square,
  Mean: Minus,
  Scatter: ChartScatter,
  Contour: ChartArea,
  "Spot — Isocenter": Crosshair,
  "Spot — Chamber": Square,
  "Timeslice — Isocenter": Clock,
  "Timeslice — Chamber": Clock,
  "Beam on": Circle,
  "Beam off": CircleOff,
  Both: CircleDot,
  All: Layers,
  "Lower 95%": ArrowDown,
  "Upper 95%": ArrowUp,
  "MAD outliers": TriangleAlert,
  position: Crosshair,
  position_error: Crosshair,
  sigma: CircleDot,
  confidence: BadgeCheck,
  coverage: Scan,
  spot: CircleDot,
  timeslice: Clock,
  all: Layers,
  on: Circle,
  off: CircleOff,
  scatter: ChartScatter,
  density: ChartArea,
  ic1_current: Zap,
  ic2_current: Zap,
  ic3_current: Zap,
  dose_rate: Gauge,
  sigma_x: CircleDot,
  sigma_y: CircleDot,
  position_x: MoveHorizontal,
  position_y: MoveVertical,
  position_error_x: MoveHorizontal,
  position_error_y: MoveVertical,
  field_x: MoveHorizontal,
  field_y: MoveVertical,
  spot_no: Hash,
  layer_id: Layers,
  r_ic1_x_confidence: BadgeCheck,
};

export function optionIcon(name: string): LucideIcon | undefined {
  return ICONS[name];
}
