[package]
name = "scan-kit-compute"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
authors.workspace = true
description = "Scan Kit wgpu compute"

[lints]
workspace = true

[dependencies]
naga = "27"
scan-kit-core = { workspace = true }
scan-kit-io = { workspace = true }
scan-kit-plot = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
wgpu = "27"

[dev-dependencies]
tokio = { workspace = true }
